CREATE TABLE IF NOT EXISTS car_description (
	entry_ID INTEGER,
	region_url VARCHAR(255),
	price INTEGER,
	manufactured_year INTEGER,
	manufacturer VARCHAR(255),
	model VARCHAR(255),
	car_condition VARCHAR(255),
	cylinders VARCHAR(255),
	fuel VARCHAR(255),
	odometer INTEGER,
	transmission VARCHAR(255),
	car_drive VARCHAR(255),
	car_size VARCHAR(255),
	car_type VARCHAR(255),
	paint_color VARCHAR(255),
	US_state VARCHAR(255),
	latitude REAL,
	longitude REAL,
)